name: CI - FAST Local Testing

on:
  push:
    branches:
      - users/*

jobs:
  build_local_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Add/Update packages
      run: |
        sudo apt-get update 
        sudo apt-get install yarn
        sudo yarn global upgrade typescript
        sudo yarn global add lerna

    - name: Install package dependencies / prepare workspaces
      run: yarn install --frozen-lockfile

    - name: Testing Prettier format
      run: lerna run prettier:diff

    - name: Testing units
      run: lerna run test --stream

    - name: Collect and upload code coverage to Code Climate
      uses: paambaati/codeclimate-action@v2.6.0
      env: 
        CC_TEST_REPORTER_ID: 08a773cb4ea5811add5a45e12873e5cd2634c005568705cc37abfd5217617a32
      with:
        coverageCommand: lerna run coverage
        coverageLocations: |
          ${{github.workspace}}/packages/tooling/fast-tooling-react/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/utilities/fast-animation/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/utilities/fast-colors/coverage/lcov.info:lcov
          ${{github.workspace}}/sites/fast-component-explorer/coverage/lcov.info:lcov
        debug: true