aliases:
  container_config: &container_config
    docker:
        - image: circleci/node:latest
    working_directory: ~/fast-dna

version: 2
jobs:
  build_and_unit_test:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install the latest NPM version and patches
          command: |
            sudo npm i npm@latest -g
            npm update rc --depth 4
      - run:
          name: Install the latest Lerna version
          command: |
            sudo npm i lerna@^3.0.6 -g
      - run:
          name: Install all dependency packages
          command: |
            npm i
      - run:
          name: Execute Lerna bootstrap
          command: |
            lerna bootstrap
      - run: 
          name: Unit Test all packages
          command: |
            lerna run test --stream
      - run:
          name: Setup and execute Code Climate reporter
          command: |
            if [ ! -f ./coverage/cc-test-reporter ]; then
              mkdir -p coverage/
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./coverage/cc-test-reporter
              chmod +x ./coverage/cc-test-reporter
            fi

            # Notify Code Climate that a build is about to start
            ./coverage/cc-test-reporter before-build

            for f in packages/*; do
              if [ -d "$f" ]; then
                echo $f
                set +e
                if [ -d "$f/coverage" ]; then
                  ./coverage/cc-test-reporter format-coverage -t lcov -o coverage/coverage.${f//\//-}.json $f/coverage/lcov.info
                fi
              fi
            done;

            ./coverage/cc-test-reporter sum-coverage -o coverage/coverage.total.json coverage/coverage.*.json
            ./coverage/cc-test-reporter upload-coverage -i coverage/coverage.total.json
      - store_test_results:
          path: ./coverage/coverage.total.json

workflows:
  version: 2
  build_test_coverage:
    jobs:
      - build_and_unit_test