aliases:
    - &container_config
        docker:
            - image: "circleci/node:latest"
        working_directory: ~/fast-dna
      
    - &node_install
        run: 
            name: Install Node
            command: |
                sudo npm i npm@latest -g
                npm update rc --depth 4

    - &lerna_install
        run: 
            name: Install Lerna
            command: |
                sudo npm i lerna@^3.0.6 -g

version: 2
jobs:
    build_dependencies:
        <<: *container_config
        steps:
            - *lerna_install
            - checkout
            - run: 
                name: Install package dependencies
                command: |
                    npm i
            - run: 
                name: Bootstrap dependencies
                command: |
                    lerna bootstrap
            - run: 
                name: Run unit tests
                command: |
                    lerna run test --stream
            - persist_to_workspace:
                root: ~/fast-dna
                paths:
                    - coverage
                    - packages/**/coverage

    test_coverage:
        <<: *container_config
        steps:
            - checkout
            - attach_workspace:
                at: ~/fast-dna
            - run:
                name: Setup and execute Code Climate reporter
                command: |
                    if [ ! -f ./coverage/cc-test-reporter ]; then
                      mkdir -p coverage/
                      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./coverage/cc-test-reporter
                      chmod +x ./coverage/cc-test-reporter
                    fi
            - run:
                name: Notify Code Climate that a build is starting
                command: |
                    ./coverage/cc-test-reporter before-build
            - run:
                name: Collect coverage reports
                command: |
                    for f in packages/*; do
                      if [ -d "$f" ]; then
                        echo $
                        set +e
                        if [ -d "$f/coverage" ]; then
                          ./coverage/cc-test-reporter format-coverage -t lcov -o coverage/coverage.${f//\//-}.json $f/coverage/lcov.info
                        fi
                      fi
                    done;
            - run:
                name: Summarize and upload code coverage
                command: |
                    ./coverage/cc-test-reporter sum-coverage -o coverage/coverage.total.json coverage/coverage.*.json
                    ./coverage/cc-test-reporter upload-coverage -i coverage/coverage.total.json

    test_browsers:
        <<: *container_config
        steps:
            - run: 
                name: Install Sauce Labs image
                command: |
                    wget https://saucelabs.com/downloads/sc-4.5.1-linux.tar.gz
                    tar -xzf sc-4.5.1-linux.tar.gz
            - run:
                name: Test on Sauce Labs
                background: true
                command: |
<<<<<<< HEAD
                    cd .circleci/
                    node test-cross-browsers.js

=======
                    cd sc-*-linux && ./bin/sc --user $SAUCELABS_USER --api-key $SAUCELABS_KEY --readyfile ~/sauce_is_ready: 
                    # Wait for tunnel to be read
                    - while [ ! -e ~/sauce_is_ready  ]; do sleep 1; done
                    - python -m hello.hello_app: 
                      background: true
                    # Wait for app to be ready
                    - curl --retry 10 --retry-delay 2 -v http://localhost:5000
                    # Run selenium tests
                    - nosetests
            - run: 
                name: Wait for Sauce Connect to close the tunnel
                command: |
                    killall --wait sc 
                  
>>>>>>> update configuration for sauce labs
workflows:
  version: 2
  build_test_coverage:
    jobs:
      - build_dependencies
      - test_coverage:
          requires: 
            - build_dependencies
      - test_browsers:
          requires:
            - build_dependencies
