name: CD - Color Explorer

on:
  pull_request:
    branches:
    - master

jobs:
  build_deploy_linux:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_ACTIVE_STAGE_NAME: color-west-app
      AZURE_WEBAPP_PASSIVE_STAGE_NAME: color-east-app
      AZURE_WEBAPP_BUILD_PATH: sites/fast-color-explorer
      AZURE_WEBAPP_DIST_PATH: sites/fast-color-explorer/www
      AZURE_WEBAPP_SLOT_NAME: stage

    steps:
    - name: Checkout Branch
      uses: actions/checkout@master

    - name: Install Lerna
      run: yarn global add lerna

    - name: Install package dependencies / prepare workspaces
      run: yarn install --frozen-lockfile
    
    - name: Build & Prepare Web Application
      run: |
        cd ${{ env.AZURE_WEBAPP_BUILD_PATH }}
        yarn build
        cp ../statics/server.js www
        cd www
        npm i
        ls -lta

    - name: 'Deploy to Active Azure Region'
      uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_COLOR_ACTIVE }}
        app-name: ${{ env.AZURE_WEBAPP_ACTIVE_STAGE_NAME }}
        package: ${{ env.AZURE_WEBAPP_DIST_PATH }}
        slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}

    - name: 'Deploy to Passive Azure Region'
      uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_COLOR_PASSIVE }}
        app-name: ${{ env.AZURE_WEBAPP_PASSIVE_STAGE_NAME }}
        package: ${{ env.AZURE_WEBAPP_DIST_PATH }}
        slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}
