name: CI - FAST

on:
  push: 
    branches:
    - master
    - releases/*
  pull_request:
    branches:
    - master
    - releases/*
    - features/*
    - feature/*

jobs:
  build_macos:
    name: Validate on MacOS
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install n
      run: npm install -g n

    - name: Update to latest Node
      run: sudo n latest

    - name: Install Lerna
      run: sudo yarn global add lerna 

    - name: Install package dependencies / prepare workspaces
      run: yarn install --frozen-lockfile

    - name: Ensure Prettier formatting
      run: lerna run prettier:diff

    - name: Execute unit tests
      run: lerna run test --stream

  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add or Update packages
      run: sudo yarn global add lerna@3.18.2

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo '::set-output name=dir::$(yarn cache dir)'

    - name: Set up node_modules cache
      uses: actions/cache@v1.1.2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install package dependencies / prepare workspaces
      run: yarn install --frozen-lockfile

    - name: Testing Prettier format
      run: lerna run prettier:diff

    - name: Testing unit tests
      run: lerna run test --stream

    - name: Collect and upload code coverage to Code Climate
      uses: paambaati/codeclimate-action@v2.6.0
      env: 
        CC_TEST_REPORTER_ID: 08a773cb4ea5811add5a45e12873e5cd2634c005568705cc37abfd5217617a32
      with:
        coverageCommand: lerna run coverage
        coverageLocations: |
          ${{github.workspace}}/packages/react/fast-components-foundation-react/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/react/fast-components-react-base/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/react/fast-components-react-msft/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/react/fast-components-styles-msft/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/react/fast-jss-manager/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/react/fast-jss-manager-react/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/react/fast-jss-utilities/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/react/fast-layouts-react/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/react/fast-react-utilities/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/tooling/fast-tooling/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/tooling/fast-tooling-react/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/utilities/fast-animation/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/utilities/fast-colors/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/utilities/fast-web-utilities/coverage/lcov.info:lcov
          ${{github.workspace}}/sites/fast-component-explorer/coverage/lcov.info:lcov
        debug: false